export const continueWatching = [
  {
    title: "Olympus",
    image: "/placeholder.svg?height=450&width=300&text=Olympus",
    year: "2023",
    category: "DRAMA",
    episodeNumber: 5,
    rating: 9.1,
  },
  {
    title: "Icarus",
    image: "/placeholder.svg?height=450&width=300&text=Icarus",
    year: "2023",
    category: "SCI-FI",
    episodeNumber: 8,
    rating: 8.8,
  },
  {
    title: "Red War",
    image: "/placeholder.svg?height=450&width=300&text=Red+War",
    year: "2023",
    category: "ACTION",
    episodeNumber: 12,
    rating: 9.3,
  },
  {
    title: "Lucretia",
    image: "/placeholder.svg?height=450&width=300&text=Lucretia",
    year: "2023",
    category: "DRAMA",
    episodeNumber: 6,
    rating: 8.9,
  },
  {
    title: "The Kingdom",
    image: "/placeholder.svg?height=450&width=300&text=The+Kingdom",
    year: "2023",
    category: "FANTASY",
    episodeNumber: 4,
    rating: 9.2,
  },
  {
    title: "Venture",
    image: "/placeholder.svg?height=450&width=300&text=Venture",
    year: "2023",
    category: "ADVENTURE",
    episodeNumber: 7,
    rating: 8.7,
  },
];

export const newUpdates = [
  {
    title: "The Crowned Jewel",
    image: "/placeholder.svg?height=450&width=300&text=The+Crowned+Jewel",
    year: "2024",
    category: "DRAMA",
    rating: 9.2,
    isNew: true,
  },
  {
    title: "Serendipity",
    image: "/placeholder.svg?height=450&width=300&text=Serendipity",
    year: "2024",
    category: "ROMANCE",
    rating: 8.9,
    isNew: true,
  },
  {
    title: "Radiant Horizons",
    image: "/placeholder.svg?height=450&width=300&text=Radiant+Horizons",
    year: "2024",
    category: "SCI-FI",
    rating: 9.4,
    isNew: true,
  },
  {
    title: "Beyond Boundaries",
    image: "/placeholder.svg?height=450&width=300&text=Beyond+Boundaries",
    year: "2024",
    category: "ACTION",
    rating: 9.1,
    isNew: true,
  },
  {
    title: "Whispers of Eternity",
    image: "/placeholder.svg?height=450&width=300&text=Whispers+of+Eternity",
    year: "2024",
    category: "FANTASY",
    rating: 9.3,
    isNew: true,
  },
  {
    title: "Luminous Dreams",
    image: "/placeholder.svg?height=450&width=300&text=Luminous+Dreams",
    year: "2024",
    category: "DRAMA",
    rating: 8.7,
    isNew: true,
  },
];
